Add more Admin logic
itayf9/Plan_It_Enigne_1.0 pull request #16
Opened 2023-05-01 20:49 UTC by Danielsio

Added more methods to admin controller and admin Engine.
1. method that will make specific user admin
2. method that qeury all users

2023-05-01 20:50 UTC, Danielsio commented
Code should be Reviewed cautiously before getting mergerd.

2023-05-02 18:35 UTC, oshriFadlon1 commented on src/main/java/com/example/planit/engine/AdminEngine.java
> +            // Check if course exists in database
// user not course

2023-05-02 18:59 UTC, Danielsio commented on src/main/java/com/example/planit/engine/AdminEngine.java
> +            // Check if course exists in database
nice catch

2023-05-03 13:38 UTC, Danielsio commented
When you are done reviewing the code changes, please leave a comment, or approve the changes, so I would know that someone is doing something. Thanks.

2023-05-03 21:49 UTC, itayf9 requested changes

2023-05-03 21:49 UTC, itayf9 commented on src/main/java/com/example/planit/engine/AdminEngine.java
> +                return new DTOusersResponseToController(false, Constants.ERROR_USER_NOT_FOUND, HttpStatus.BAD_REQUEST);
The constant : `Constants.ERROR_USER_NOT_FOUND` is returned in the response both when the admin user is not in the DB (line 196)  and when the user to be converted is not in the DB (line 202).

2023-05-03 22:23 UTC, itayf9 commented on src/main/java/com/example/planit/engine/AdminEngine.java
> +                return new DTOusersResponseToController(false, Constants.ERROR_USER_NOT_FOUND, HttpStatus.BAD_REQUEST);
The issue #18 will fix that problem, which is in a greater scale, in the future. So I think this PR can be merged.

2023-05-03 22:24 UTC, itayf9 approved these changes

2023-05-03 22:25 UTC, merged