readme file and readmeObjects
itayf9/Plan_It_Enigne_1.0 pull request #23
Opened 2023-05-06 18:41 UTC by oshriFadlon1

I add readme file and all the object that need for it.

2023-05-06 20:06 UTC, Danielsio approved these changes

2023-05-12 18:22 UTC, Danielsio commented
can you get a PR of readme for Plan-IT-vite as well ?

2023-05-13 15:19 UTC, itayf9 requested changes

2023-05-13 15:19 UTC, itayf9 commented on README.md
> +![Logo](https://github.com/oshriFadlon1/Plan_It_Enigne_1.0/blob/master/Plan.png)
I think this link has the wrong url

2023-05-13 15:21 UTC, Danielsio commented on README.md
> +- [@oshriFadlon1](https://github.com/oshriFadlon1)
drop the @

2023-05-14 18:43 UTC, Danielsio approved these changes

2023-05-16 22:32 UTC, itayf9 approved these changes
Seems good to me

2023-05-16 22:33 UTC, merged