Fix updateHolidays
itayf9/Plan_It_Enigne_1.0 pull request #29
Opened 2023-06-03 17:33 UTC by Danielsio

This PR shows how you can connect objects accross the application with @Autowired, i connected new Wrapper object called PlanItHolidays that holds list of holidays.

it allows me to set the list in the object to the newly updated holidays in admin engine, admin engine must be declared as @Service in order for it to get access to the singelton PlanItHolidays

2023-07-02 13:59 UTC, Danielsio commented on pom.xml
> +
need to configure github secrets, as of right now, test class is excluded so ci wont fail

2023-07-11 22:19 UTC, Danielsio commented
I assume tests are failing because there are no secrets configured yet

2023-07-13 12:48 UTC, oshriFadlon1 approved these changes
look good

2023-07-18 20:00 UTC, itayf9 requested changes

2023-07-18 20:00 UTC, itayf9 commented on .github/workflows/maven.yml
> +#
@Danielsio  Did you comment that in order to use it in the future? Or it needs to be removed?

2023-07-18 20:00 UTC, itayf9 commented on src/main/java/com/example/planit/controller/AdminController.java
> +        DTOResponseToController dtOholidaysResponseToController = adminEngine.updateHolidays(sub);
@Danielsio If changed the type, I think you should also change the varable name (maybe dtoResponseToController)

2023-07-18 20:00 UTC, itayf9 commented on src/main/java/com/example/planit/utill/dto/DTOResponseToController.java
> +public class DTOResponseToController extends DTOstatus {
@Danielsio Just for the convension in the other DTO names in our code, the "R" should be lower cased in `DTOResponseToController`

2023-07-18 22:21 UTC, Danielsio commented on .github/workflows/maven.yml
> +#
I had a good responsible reason for not deleteing those lines, but right now it's not relevent anymore.

Those line will be removed.

2023-07-18 22:22 UTC, Danielsio commented on src/main/java/com/example/planit/controller/AdminController.java
> +        DTOResponseToController dtOholidaysResponseToController = adminEngine.updateHolidays(sub);
yes, my bad.

2023-07-18 22:24 UTC, Danielsio commented on src/main/java/com/example/planit/utill/dto/DTOResponseToController.java
> +public class DTOResponseToController extends DTOstatus {
done

2023-07-18 22:43 UTC, Danielsio commented
Also dont worry about all the commits, you dont have to use ammend to make all the changes apear in single commit.
the decision is all yours if you think code review will be easier with multiple commits go for it. 

then you merge the PR, you can do "Squash commits & Merge" which will force all the commits to apear as single commit anyway so you dont have to work extra hard for that.

2023-07-19 20:20 UTC, itayf9 requested changes

2023-07-19 20:20 UTC, itayf9 commented on src/main/java/com/example/planit/engine/CalendarEngine.java
> +    String CLIENT_SECRET;
@Danielsio  Add access modifiers.

2023-07-19 20:20 UTC, Danielsio commented on src/main/java/com/example/planit/engine/CalendarEngine.java
> +    String CLIENT_SECRET;
done

2023-07-19 20:21 UTC, itayf9 approved these changes

2023-07-19 20:24 UTC, merged