Fix duplicate fullDayEvent
itayf9/Plan_It_Enigne_1.0 pull request #63
Opened 2023-07-31 18:31 UTC by Danielsio

Fixed bug of duplicate full day events Refer to #59
problem was that after Add full-day-events from DB the full day events list wasnt sorted, i applied a sort + rewrote the EventComparator to be more readable

close #59

if you are still afraid to merge this PR, please tell me and i will add more tests to prove the comparator is not broken.

2023-07-31 22:17 UTC, itayf9 requested changes

2023-07-31 22:17 UTC, itayf9 commented on src/main/java/com/example/planit/engine/CalendarEngine.java
>              }
@Danielsio Add some documentation explaining the else case being ignored.

2023-08-02 22:11 UTC, oshriFadlon1 approved these changes

2023-08-02 22:12 UTC, itayf9 approved these changes
Great work Daniel! All good.

2023-08-02 22:27 UTC, merged